package codexbridge

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const Provider = "codex_account"

func IsProvider(p string) bool { return strings.EqualFold(strings.TrimSpace(p), Provider) }

type Model struct {
	Model     string `json:"model"`
	IsDefault bool   `json:"isDefault"`
}
type Status struct {
	LoggedIn     bool                   `json:"logged_in"`
	AccountType  string                 `json:"account_type"`
	Models       []Model                `json:"models"`
	OutputBudget OutputBudgetCapability `json:"output_budget"`
}

// OutputBudgetCapability describes the bridge contract, not a provider quota.
// The protocol generated by codex-cli 0.150.0-alpha.12.2 has no hard output-token
// limit in TurnStartParams, ThreadStartParams, or Config. Never send invented
// max_tokens parameters or present an instruction budget as a server limit.
type OutputBudgetCapability struct {
	Mode                  string `json:"mode"`
	HardLimitSupported    bool   `json:"hard_limit_supported"`
	CallOverrideSupported bool   `json:"call_override_supported"`
}

func OutputBudgetSupport() OutputBudgetCapability {
	return OutputBudgetCapability{Mode: "advisory", CallOverrideSupported: true}
}

type Request struct {
	Model, Effort, Instructions, Input string
	OutputSchema                       any
	// MaxOutputTokens is a soft instruction budget, including reasoning and JSON.
	// Zero leaves it unspecified; it is not a server-enforced generation limit.
	MaxOutputTokens int
}
type Result struct {
	Text                                                                    string
	InputTokens, OutputTokens, TotalTokens                                  int
	CachedInputTokens, ReasoningOutputTokens, CacheWriteInputTokens         int
	UsageReported, CachedInputTokensReported, ReasoningOutputTokensReported bool
	CacheWriteInputTokensReported                                           bool
}

// Field names match the locally generated TokenUsageBreakdown schema. Pointers
// preserve the difference between a measured zero and an omitted detail.
type tokenUsageBreakdown struct {
	Input           int  `json:"inputTokens"`
	Output          int  `json:"outputTokens"`
	Total           int  `json:"totalTokens"`
	CachedInput     *int `json:"cachedInputTokens"`
	ReasoningOutput *int `json:"reasoningOutputTokens"`
	CacheWriteInput *int `json:"cacheWriteInputTokens"`
}

func (r *Result) setUsage(usage *tokenUsageBreakdown) {
	if usage == nil {
		return
	}
	r.UsageReported = true
	r.InputTokens, r.OutputTokens, r.TotalTokens = usage.Input, usage.Output, usage.Total
	r.CachedInputTokensReported = usage.CachedInput != nil
	r.ReasoningOutputTokensReported = usage.ReasoningOutput != nil
	r.CacheWriteInputTokensReported = usage.CacheWriteInput != nil
	r.CachedInputTokens, r.ReasoningOutputTokens, r.CacheWriteInputTokens = 0, 0, 0
	if usage.CachedInput != nil {
		r.CachedInputTokens = *usage.CachedInput
	}
	if usage.ReasoningOutput != nil {
		r.ReasoningOutputTokens = *usage.ReasoningOutput
	}
	if usage.CacheWriteInput != nil {
		r.CacheWriteInputTokens = *usage.CacheWriteInput
	}
}

func instructionsWithOutputBudget(req Request) string {
	if req.MaxOutputTokens <= 0 {
		return req.Instructions
	}
	return req.Instructions + fmt.Sprintf("\n\nThe host requests a soft output budget of at most %d tokens for this response, including reasoning, text, and tool-call JSON. Keep reasoning and explanations concise. Always finish valid, complete JSON when a schema is required; reduce optional detail instead of cutting off JSON or tool arguments.", req.MaxOutputTokens)
}

type packet struct {
	ID     json.RawMessage `json:"id,omitempty"`
	Method string          `json:"method,omitempty"`
	Params json.RawMessage `json:"params,omitempty"`
	Result json.RawMessage `json:"result,omitempty"`
	Error  *struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	} `json:"error,omitempty"`
}
type Client struct {
	cmd      *exec.Cmd
	in       io.WriteCloser
	packets  chan packet
	done     chan struct{}
	cancel   context.CancelFunc
	readErr  error
	id       int
	cwd      string
	mcpNames []string
}

var disabledFeatures = []string{"shell_tool", "unified_exec", "code_mode", "code_mode_host", "apps", "plugins", "browser_use", "browser_use_external", "computer_use", "image_generation", "multi_agent", "hooks", "skill_search", "skill_mcp_dependency_install", "view_image", "workspace_dependencies", "goals", "shell_snapshot", "unbounded_connection_retries"}

// Start uses only the server administrator's executable/environment, never HTTP
// input. Codex retains ownership of its login credentials; auth.json is not read.
func Start(ctx context.Context) (*Client, error) {
	bin := strings.TrimSpace(os.Getenv("CYBERSTRIKE_CODEX_BIN"))
	if bin == "" {
		var err error
		bin, err = exec.LookPath("codex")
		if err != nil {
			return nil, errors.New("未找到 Codex CLI；请安装并执行 codex login")
		}
	}
	cwd := os.Getenv("CYBERSTRIKE_CODEX_WORKDIR")
	if cwd == "" {
		exe, err := os.Executable()
		if err != nil {
			return nil, err
		}
		cwd = filepath.Join(filepath.Dir(exe), ".codex-bridge")
	}
	cwd, err := filepath.Abs(cwd)
	if err != nil {
		return nil, err
	}
	if err = os.MkdirAll(cwd, 0700); err != nil {
		return nil, err
	}
	args := []string{"app-server", "--listen", "stdio://", "-c", `approval_policy="on-request"`, "-c", `approvals_reviewer="user"`, "-c", `web_search="disabled"`, "-c", "notify=[]", "-c", "project_doc_max_bytes=0"}
	for _, f := range disabledFeatures {
		args = append(args, "--disable", f)
	}
	processCtx, cancel := context.WithCancel(ctx)
	cmd := exec.CommandContext(processCtx, bin, args...)
	cmd.Dir = cwd
	cmd.Env = accountEnvironment(os.Environ())
	hideWindow(cmd)
	in, err := cmd.StdinPipe()
	if err != nil {
		cancel()
		return nil, err
	}
	out, err := cmd.StdoutPipe()
	if err != nil {
		cancel()
		in.Close()
		return nil, err
	}
	cmd.Stderr = io.Discard // Diagnostic output can contain local account/config data.
	if err = cmd.Start(); err != nil {
		cancel()
		in.Close()
		out.Close()
		return nil, fmt.Errorf("start Codex: %w", err)
	}
	c := &Client{cmd: cmd, in: in, packets: make(chan packet, 32), done: make(chan struct{}), cancel: cancel, cwd: cwd}
	go c.read(processCtx, out)
	initCtx, initCancel := context.WithTimeout(ctx, 30*time.Second)
	defer initCancel()
	_, err = c.call(initCtx, "initialize", map[string]any{"clientInfo": map[string]any{"name": "cyberstrike_codex_bridge", "version": "1.0.0"}, "capabilities": map[string]any{"experimentalApi": true}}, nil)
	if err == nil {
		err = c.write(map[string]any{"method": "initialized", "params": map[string]any{}})
	}
	if err == nil {
		var raw json.RawMessage
		raw, err = c.call(initCtx, "config/read", map[string]any{"includeLayers": false}, nil)
		if err == nil {
			var cfg struct {
				Config struct {
					MCP map[string]any `json:"mcp_servers"`
				} `json:"config"`
			}
			if err = json.Unmarshal(raw, &cfg); err == nil {
				for name := range cfg.Config.MCP {
					c.mcpNames = append(c.mcpNames, name)
				}
			}
		}
	}
	if err != nil {
		c.Close()
		return nil, err
	}
	return c, nil
}
func accountEnvironment(env []string) []string {
	out := make([]string, 0, len(env))
	for _, v := range env {
		k, _, _ := strings.Cut(v, "=")
		if strings.EqualFold(k, "OPENAI_API_KEY") || strings.EqualFold(k, "CODEX_API_KEY") {
			continue
		}
		out = append(out, v)
	}
	return out
}
func (c *Client) read(ctx context.Context, r io.Reader) {
	defer close(c.done)
	defer close(c.packets)
	s := bufio.NewScanner(r)
	s.Buffer(make([]byte, 65536), 32*1024*1024)
	for s.Scan() {
		var p packet
		if err := json.Unmarshal(s.Bytes(), &p); err != nil {
			c.readErr = errors.New("invalid Codex protocol JSON")
			return
		}
		select {
		case c.packets <- p:
		case <-ctx.Done():
			return
		}
	}
	c.readErr = s.Err()
}
func (c *Client) Close() {
	if c == nil || c.cmd == nil {
		return
	}
	c.in.Close()
	c.cancel()
	_ = c.cmd.Wait()
	<-c.done
	c.cmd = nil
}
func (c *Client) write(v any) error { return json.NewEncoder(c.in).Encode(v) }
func (c *Client) receive(ctx context.Context) (packet, error) {
	select {
	case <-ctx.Done():
		return packet{}, ctx.Err()
	case p, ok := <-c.packets:
		if !ok {
			if c.readErr != nil {
				return packet{}, c.readErr
			}
			return packet{}, errors.New("Codex app-server exited; check CLI version and login status")
		}
		return p, nil
	}
}

var mcpNamePattern = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

var secretPattern = regexp.MustCompile(`(?i)(sk-[a-z0-9_-]+|eyJ[a-z0-9_.-]{30,})`)

func safeError(s string) string {
	s = secretPattern.ReplaceAllString(s, "[REDACTED]")
	if len(s) > 500 {
		s = s[:500]
	}
	return s
}

// Built-in Codex execution is denied. Application tools are executed only by
// Eino, through the application's existing role and approval middleware.
func (c *Client) handle(p packet, notify func(packet) error) error {
	if p.Method != "" && len(p.ID) > 0 {
		var result any
		switch p.Method {
		case "item/commandExecution/requestApproval", "item/fileChange/requestApproval":
			result = map[string]any{"decision": "decline"}
		case "execCommandApproval", "applyPatchApproval":
			result = map[string]any{"decision": "denied"}
		case "item/permissions/requestApproval":
			result = map[string]any{"permissions": map[string]any{}, "scope": "turn"}
		default:
			return c.write(map[string]any{"id": p.ID, "error": map[string]any{"code": -32601, "message": "Use application-managed tools; Codex tools are disabled."}})
		}
		return c.write(map[string]any{"id": p.ID, "result": result})
	}
	if p.Method != "" && notify != nil {
		return notify(p)
	}
	return nil
}
func (c *Client) call(ctx context.Context, method string, params any, notify func(packet) error) (json.RawMessage, error) {
	c.id++
	id := c.id
	if err := c.write(map[string]any{"id": id, "method": method, "params": params}); err != nil {
		return nil, err
	}
	for {
		p, err := c.receive(ctx)
		if err != nil {
			return nil, err
		}
		if p.Method == "" && string(p.ID) == fmt.Sprint(id) {
			if p.Error != nil {
				return nil, fmt.Errorf("Codex %s (%d): %s", method, p.Error.Code, safeError(p.Error.Message))
			}
			return p.Result, nil
		}
		if err = c.handle(p, notify); err != nil {
			return nil, err
		}
	}
}
func (c *Client) requireAccount(ctx context.Context) error {
	raw, err := c.call(ctx, "account/read", map[string]any{"refreshToken": false}, nil)
	if err != nil {
		return err
	}
	var v struct {
		Account *struct {
			Type string `json:"type"`
		} `json:"account"`
	}
	if err = json.Unmarshal(raw, &v); err != nil {
		return err
	}
	if v.Account == nil || v.Account.Type != "chatgpt" {
		return errors.New("此通道需要 ChatGPT 登录；请在服务所在 Windows 账号下执行 codex login（不会回退到 API Key）")
	}
	return nil
}
func (c *Client) Models(ctx context.Context) ([]Model, error) {
	if err := c.requireAccount(ctx); err != nil {
		return nil, err
	}
	var models []Model
	var cursor any
	for page := 0; page < 20; page++ {
		raw, err := c.call(ctx, "model/list", map[string]any{"limit": 100, "includeHidden": false, "cursor": cursor}, nil)
		if err != nil {
			return nil, err
		}
		var v struct {
			Data       []Model `json:"data"`
			NextCursor *string `json:"nextCursor"`
		}
		if err = json.Unmarshal(raw, &v); err != nil {
			return nil, err
		}
		models = append(models, v.Data...)
		if v.NextCursor == nil || *v.NextCursor == "" {
			return models, nil
		}
		cursor = *v.NextCursor
	}
	return nil, errors.New("Codex model pagination exceeded limit")
}
func Check(ctx context.Context) (*Status, error) {
	ctx, cancel := context.WithTimeout(ctx, 40*time.Second)
	defer cancel()
	c, err := Start(ctx)
	if err != nil {
		return nil, err
	}
	defer c.Close()
	models, err := c.Models(ctx)
	if err != nil {
		return nil, err
	}
	return &Status{LoggedIn: true, AccountType: "chatgpt", Models: models, OutputBudget: OutputBudgetSupport()}, nil
}
func (c *Client) Run(ctx context.Context, req Request, onDelta func(string) error) (*Result, error) {
	if req.MaxOutputTokens < 0 {
		return nil, errors.New("Codex soft output token budget cannot be negative")
	}
	if err := c.requireAccount(ctx); err != nil {
		return nil, err
	}
	if strings.TrimSpace(req.Model) == "" {
		return nil, errors.New("Codex model is required")
	}
	overrides := map[string]any{}
	for _, name := range c.mcpNames {
		// App Server override keys are split on dots, not parsed as TOML keys.
		// Reject ambiguous names instead of leaving an inherited server enabled.
		if !mcpNamePattern.MatchString(name) {
			return nil, errors.New("Codex MCP name cannot be isolated safely; use only letters, digits, underscores, and hyphens")
		}
		overrides["mcp_servers."+name+".enabled"] = false
	}
	raw, err := c.call(ctx, "thread/start", map[string]any{"model": req.Model, "modelProvider": "openai", "cwd": c.cwd, "ephemeral": true, "approvalPolicy": "on-request", "approvalsReviewer": "user", "sandbox": "read-only", "baseInstructions": instructionsWithOutputBudget(req), "config": overrides}, nil)
	if err != nil {
		return nil, err
	}
	var started struct {
		Thread struct {
			ID string `json:"id"`
		} `json:"thread"`
	}
	if err = json.Unmarshal(raw, &started); err != nil {
		return nil, err
	}
	threadID := started.Thread.ID
	if threadID == "" {
		return nil, errors.New("Codex returned no thread id")
	}
	result := &Result{}
	completed := false
	var turnErr error
	var streamed strings.Builder
	notify := func(p packet) error {
		var v struct {
			ThreadID string `json:"threadId"`
			Delta    string `json:"delta"`
			Item     struct {
				Type  string `json:"type"`
				Text  string `json:"text"`
				Phase string `json:"phase"`
			} `json:"item"`
			Turn struct {
				Status string `json:"status"`
				Error  *struct {
					Message string `json:"message"`
				} `json:"error"`
			} `json:"turn"`
			TokenUsage struct {
				Last  *tokenUsageBreakdown `json:"last"`
				Total *tokenUsageBreakdown `json:"total"`
			} `json:"tokenUsage"`
		}
		if err := json.Unmarshal(p.Params, &v); err != nil {
			return err
		}
		if v.ThreadID != "" && v.ThreadID != threadID {
			return nil
		}
		switch p.Method {
		case "item/agentMessage/delta":
			if streamed.Len()+len(v.Delta) > 16*1024*1024 {
				return errors.New("Codex output exceeds 16 MiB")
			}
			streamed.WriteString(v.Delta)
			if onDelta != nil {
				return onDelta(v.Delta)
			}
		case "item/completed":
			if v.Item.Type == "agentMessage" && (v.Item.Phase == "" || v.Item.Phase == "final_answer") {
				result.Text = v.Item.Text
			}
		case "thread/tokenUsage/updated":
			// Every Run owns a fresh ephemeral thread. Its total covers all model
			// requests in this run; last can omit earlier internal attempts. These
			// are absolute counters, so repeated notifications must not be added.
			usage := v.TokenUsage.Total
			if usage == nil {
				usage = v.TokenUsage.Last
			}
			result.setUsage(usage)
		case "turn/completed":
			completed = true
			if v.Turn.Status != "completed" {
				turnErr = fmt.Errorf("Codex turn %s", v.Turn.Status)
				if v.Turn.Error != nil {
					turnErr = fmt.Errorf("Codex: %s", safeError(v.Turn.Error.Message))
				}
			}
		}
		return nil
	}
	params := map[string]any{"threadId": threadID, "input": []any{map[string]any{"type": "text", "text": req.Input, "text_elements": []any{}}}, "approvalPolicy": "on-request", "sandboxPolicy": map[string]any{"type": "readOnly", "networkAccess": false}}
	if req.Effort != "" {
		params["effort"] = req.Effort
	}
	if req.OutputSchema != nil {
		params["outputSchema"] = req.OutputSchema
	}
	if _, err = c.call(ctx, "turn/start", params, notify); err != nil {
		return result, err
	}
	for !completed {
		p, e := c.receive(ctx)
		if e != nil {
			return result, e
		}
		if err = c.handle(p, notify); err != nil {
			return result, err
		}
	}
	if turnErr != nil {
		return result, turnErr
	}
	if result.Text == "" {
		result.Text = streamed.String()
	}
	if result.Text == "" {
		return result, errors.New("Codex returned an empty response")
	}
	return result, nil
}
